"""Write requirements.lock: the exact versions this project currently runs on.

requirements.txt says what the project needs ("pandas>=2.2"). That is for humans
and stays loose. requirements.lock says what it was last verified against
("pandas==3.0.5"), so a fresh clone reproduces a working environment instead of
whatever happens to be current that week.

    python scripts/pin_requirements.py           # write the lock
    python scripts/pin_requirements.py --check   # exit 1 if it is stale

Rebuild from a lock with:  pip install -r requirements.lock
"""
import argparse, datetime, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "requirements.lock"
# Local editable install; recorded by pyproject, not by a pinned version.
SKIP = {"streetymology"}


def freeze():
    out = subprocess.run(
        [sys.executable, "-m", "pip", "freeze", "--exclude-editable"],
        capture_output=True, text=True, check=True,
    ).stdout
    lines = [l.strip() for l in out.splitlines() if "==" in l]
    return sorted(l for l in lines if l.split("==")[0].lower() not in SKIP)


def render(pins):
    stamp = datetime.date.today().isoformat()
    head = [
        "# Exact versions this project was last verified against.",
        "# Generated by scripts/pin_requirements.py -- do not hand-edit.",
        f"# python {sys.version.split()[0]}, generated {stamp}",
        "",
    ]
    return "\n".join(head + pins) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="compare only; do not write")
    a = ap.parse_args()

    pins = freeze()
    new = render(pins)

    if a.check:
        if not LOCK.exists():
            print("requirements.lock missing; run without --check")
            return 1
        old = [l for l in LOCK.read_text().splitlines() if "==" in l]
        added = sorted(set(pins) - set(old))
        removed = sorted(set(old) - set(pins))
        if not added and not removed:
            print(f"requirements.lock current, {len(pins)} packages")
            return 0
        for l in removed:
            print(f"  -{l}")
        for l in added:
            print(f"  +{l}")
        print(f"stale: {len(added)} added, {len(removed)} removed")
        return 1

    LOCK.write_text(new)
    LOCK.chmod(0o664)
    print(f"wrote {LOCK.relative_to(ROOT)}, {len(pins)} packages pinned")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
